/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DetailsRouteImport } from './routes/details'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAdminSendEmailsRouteImport } from './routes/api/admin.send-emails'
import { Route as ApiAdminResetAuctionRouteImport } from './routes/api/admin.reset-auction'
import { Route as ApiAdminMarkWinnerRouteImport } from './routes/api/admin.mark-winner'
import { Route as ApiAdminEndAuctionRouteImport } from './routes/api/admin.end-auction'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DetailsRoute = DetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSendEmailsRoute = ApiAdminSendEmailsRouteImport.update({
  id: '/api/admin/send-emails',
  path: '/api/admin/send-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminResetAuctionRoute = ApiAdminResetAuctionRouteImport.update({
  id: '/api/admin/reset-auction',
  path: '/api/admin/reset-auction',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMarkWinnerRoute = ApiAdminMarkWinnerRouteImport.update({
  id: '/api/admin/mark-winner',
  path: '/api/admin/mark-winner',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEndAuctionRoute = ApiAdminEndAuctionRouteImport.update({
  id: '/api/admin/end-auction',
  path: '/api/admin/end-auction',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/details': typeof DetailsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/api/admin/end-auction': typeof ApiAdminEndAuctionRoute
  '/api/admin/mark-winner': typeof ApiAdminMarkWinnerRoute
  '/api/admin/reset-auction': typeof ApiAdminResetAuctionRoute
  '/api/admin/send-emails': typeof ApiAdminSendEmailsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/details': typeof DetailsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/api/admin/end-auction': typeof ApiAdminEndAuctionRoute
  '/api/admin/mark-winner': typeof ApiAdminMarkWinnerRoute
  '/api/admin/reset-auction': typeof ApiAdminResetAuctionRoute
  '/api/admin/send-emails': typeof ApiAdminSendEmailsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/details': typeof DetailsRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/api/admin/end-auction': typeof ApiAdminEndAuctionRoute
  '/api/admin/mark-winner': typeof ApiAdminMarkWinnerRoute
  '/api/admin/reset-auction': typeof ApiAdminResetAuctionRoute
  '/api/admin/send-emails': typeof ApiAdminSendEmailsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/details'
    | '/leaderboard'
    | '/login'
    | '/api/admin/end-auction'
    | '/api/admin/mark-winner'
    | '/api/admin/reset-auction'
    | '/api/admin/send-emails'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/details'
    | '/leaderboard'
    | '/login'
    | '/api/admin/end-auction'
    | '/api/admin/mark-winner'
    | '/api/admin/reset-auction'
    | '/api/admin/send-emails'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/details'
    | '/leaderboard'
    | '/login'
    | '/api/admin/end-auction'
    | '/api/admin/mark-winner'
    | '/api/admin/reset-auction'
    | '/api/admin/send-emails'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DetailsRoute: typeof DetailsRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  ApiAdminEndAuctionRoute: typeof ApiAdminEndAuctionRoute
  ApiAdminMarkWinnerRoute: typeof ApiAdminMarkWinnerRoute
  ApiAdminResetAuctionRoute: typeof ApiAdminResetAuctionRoute
  ApiAdminSendEmailsRoute: typeof ApiAdminSendEmailsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/details': {
      id: '/details'
      path: '/details'
      fullPath: '/details'
      preLoaderRoute: typeof DetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/send-emails': {
      id: '/api/admin/send-emails'
      path: '/api/admin/send-emails'
      fullPath: '/api/admin/send-emails'
      preLoaderRoute: typeof ApiAdminSendEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/reset-auction': {
      id: '/api/admin/reset-auction'
      path: '/api/admin/reset-auction'
      fullPath: '/api/admin/reset-auction'
      preLoaderRoute: typeof ApiAdminResetAuctionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/mark-winner': {
      id: '/api/admin/mark-winner'
      path: '/api/admin/mark-winner'
      fullPath: '/api/admin/mark-winner'
      preLoaderRoute: typeof ApiAdminMarkWinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/end-auction': {
      id: '/api/admin/end-auction'
      path: '/api/admin/end-auction'
      fullPath: '/api/admin/end-auction'
      preLoaderRoute: typeof ApiAdminEndAuctionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DetailsRoute: DetailsRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ApiAdminEndAuctionRoute: ApiAdminEndAuctionRoute,
  ApiAdminMarkWinnerRoute: ApiAdminMarkWinnerRoute,
  ApiAdminResetAuctionRoute: ApiAdminResetAuctionRoute,
  ApiAdminSendEmailsRoute: ApiAdminSendEmailsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
